"""Added location fields and cache tables

Revision ID: df05b5c493ff
Revises: 9e60e37f6dd3
Create Date: 2026-02-25 20:19:11.459494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df05b5c493ff'
down_revision: Union[str, Sequence[str], None] = '9e60e37f6dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodity_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('commodity_group', sa.String(), nullable=True),
    sa.Column('msp', sa.String(), nullable=True),
    sa.Column('price_latest', sa.String(), nullable=True),
    sa.Column('price_mid', sa.String(), nullable=True),
    sa.Column('price_old', sa.String(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodity_cache_commodity'), 'commodity_cache', ['commodity'], unique=False)
    op.create_index(op.f('ix_commodity_cache_district'), 'commodity_cache', ['district'], unique=False)
    op.create_index(op.f('ix_commodity_cache_id'), 'commodity_cache', ['id'], unique=False)
    op.create_index(op.f('ix_commodity_cache_state'), 'commodity_cache', ['state'], unique=False)
    op.create_table('weather_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('forecast_data', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_cache_id'), 'weather_cache', ['id'], unique=False)
    op.create_index(op.f('ix_weather_cache_user_id'), 'weather_cache', ['user_id'], unique=False)
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('district', sa.String(), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'district')
    op.drop_column('users', 'state')
    op.drop_index(op.f('ix_weather_cache_user_id'), table_name='weather_cache')
    op.drop_index(op.f('ix_weather_cache_id'), table_name='weather_cache')
    op.drop_table('weather_cache')
    op.drop_index(op.f('ix_commodity_cache_state'), table_name='commodity_cache')
    op.drop_index(op.f('ix_commodity_cache_id'), table_name='commodity_cache')
    op.drop_index(op.f('ix_commodity_cache_district'), table_name='commodity_cache')
    op.drop_index(op.f('ix_commodity_cache_commodity'), table_name='commodity_cache')
    op.drop_table('commodity_cache')
    # ### end Alembic commands ###
