name: agriassist
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.5.4
  flutter_markdown: ^0.6.15
  flutter_tts: ^3.8.5
  speech_to_text: ^7.3.0
  csv: ^6.0.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0
  http: ^1.2.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf

  assets:
    - assets/images/farmer_character.png
    - assets/images/farmer_listening.png
    - assets/images/weather/sunny.png
    - assets/images/weather/cloudy.png
    - assets/images/weather/rain.png
    - assets/images/weather/default.png
    - assets/images/weather/storm.png
    - assets/images/weather/sprinkle.png
    - assets/data/cleaned_schemes.csv